### ISSUE TITLE
RegisterPlusNextWord interprets offset as unsigned, however it is signed.

### ISSUE THREAD

**Issue by JeremyWildsmith** [dangermccann/dcpu16-ide#16]
emulator.js, line 30
````
RegisterPlusNextWord.prototype.getB = RegisterPlusNextWord.prototype.getA = RegisterPlusNextWord.prototype.get = function() { 
	var nw = this.emulator.nextWord();
	if(nw == 0xffff) nw = -1;	// TODO: why is this like this???? (required for '99 bottles' to work...)
	this.cachedResult = this.register.get() + nw;
	return this.emulator.RAM[this.cachedResult] || 0; 
}
````
nw should be interpreted as a signed number. 0xFFFF translated to -1, 0xFFFE translates to -2 etc...

Most of the material on the internet appears to agree interpreting the offset as a signed integer.

This could be changed to something like 

````
...
   var nw = this.emulator.nextWord();

    if ((nw & 0x8000) !== 0) {
        nw = -((nw ^ 0xFFFF) + 1)
    }
...
````

**Comment by dangermccann** [comment]
Interesting...so should values stored in registers also be treated as signed for the purposes of arithmetic instructions (ADD, SUB, MUL, DIV)?

**Comment by JeremyWildsmith** [comment]
Hey so I am looking into this deeper, and actually I think it is a little more complex than I was mentioning. I.e, consider:

On a 16-bit platform:
0xFFFF (-1) + 3 (0x0003) = 0x0002

So I shouldn't have to do anything special to "add" a negative number.

The actual problem appears to come from here:

''''
        this.cachedResult = this.register.get() + nw;
	return this.emulator.RAM[this.cachedResult] || 0; 
''''
After the addition, the result should be and'ed with 0xFFFF to emulate a 16 bit machine.

This is actually done correctly in ADD:

````
		ADD: new Op(this, "ADD", OPERATION_ADD, 2, function(a, b) { 
			var res = a.getA() + b.getB();
			if((res & 0xffff0000) > 0)
				this.emulator.Registers.EX.set(0x0001);
			else
				this.emulator.Registers.EX.set(0);
			b.set(res & 0xffff);
		}),
````

MUL and DIV have their MLI and DVI counter parts, so I think they are an exception.

**Comment by dangermccann** [comment]
Right you are.  Thanks!
