### ISSUE TITLE
DIV Instruction not working for large numbers

### ISSUE THREAD

**Issue by JeremyWildsmith** [dangermccann/dcpu16-ide#17]
Consider
````
set a, 0x9503
div a, a
````

And refer to DIV implementation:

````
			var aVal = a.getA(), bVal = b.getB();
			if(aVal === 0) {
				this.emulator.Registers.EX.set(0);
				b.set(0);
			}
			else {			
				var res = Math.floor(bVal / aVal);
				this.emulator.Registers.EX.set(Math.floor(((bVal << 16) / aVal)) & 0xffff);
				b.set(res & 0xffff);
			}
````

Note that javascript, during a bitwise shift, treats numbers as 32 bit integers. So this will actually produce a negative number (when the intention is to interpret it as an unsigned integer.)

The result, therefore, ends up being incorrect. A possible proper implementation may be:

````
		if(aVal === 0) {
			this.emulator.Registers.EX.set(0);
			b.set(0);
		}
		else {			
                	var res = Math.floor(bVal / aVal);

                	var properShift = (bVal << 16) >>> 0
                	this.emulator.Registers.EX.set(Math.floor((properShift / aVal)) & 0xffff);
			b.set(res & 0xffff);
		}
````

**Comment by dangermccann** [comment]
Well that explains why my unit test for large number division never correctly set the EX register.  Thanks for your help!
