### ISSUE TITLE
PC Stuck in-between instructions

### ISSUE THREAD

**Issue by JeremyWildsmith** [dangermccann/dcpu16-ide#18]
Consider the below code:

````
0x0000 set [0xFFFF], pc
0x0002 set pc, [0xFFFF]
````
Executing this code in the emulator will set PC to 1 after the second instruction is executed, which is stuck in between the first and second instruction. After this, execution continues from half a instruction (results basically in PC miss-aligning with the program.)

The only emulators I've seen pass this test set [0xFFFF] to be equal to 0x0002.

I have looked into fixing this but there is no quick fix from the way the emulator is structured that I can find.  I may look into this later tomorrow, however I believed it is worth mentioning.

**Comment by dangermccann** [comment]
I figured out a relatively harmless workaround.

**Comment by JeremyWildsmith** [comment]
Hey, thanks.

You need to be careful with patching this one, I thought of the solution you provided but it isn't complete.

Consider (and I know that this is very odd code, but it could manifest in some reasonably logical code):

````
0x0000 set [0xFFFF], 2
0x0002 mul [0xFFFF], pc
0x0004 div [0xFFFF], 2
0x0006 set pc, [0xFFFF]
````

PC will be equal to 3 after the last step. Expected behavior would be 0x0004 (To be consistent with the patched behavior) You could apply your changes to the "set" instruction to all other instructions that accept operands 

However, I don't think that would be sufficient coverage, consider:

````
set [pc], 0x8781 ;0x8781 is opcode for set pc, 0
set x, 10
set pc, fail

:fail
set pc, fail
````

PC has to be valid throughout the entire execution of an instruction.

Thanks,
